# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 08:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180117_1617'),
        ('invitations', '0003_auto_20151126_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_company', to='companies.Company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
