# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20180119_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='superuser_status',
            field=models.BooleanField(default=False),
        ),
    ]
