# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_invitation_superuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='employee_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
